require("prototypes.entity.__init__")
require("prototypes.item.items-turrets")
require("prototypes.item.item-ammo")
--require("prototypes.item.item-walls")
require("prototypes.recipe.recipe-weapons")
--require("prototypes.recipe.flamethrower-turret-mk2")
require("prototypes.technology.technology-weapons")
--require("prototypes.technology.flamethrower-turret-mk2")
